// export const restaurants = [
//     {
//         name: 'Subway',
//         rating: 4.3,
//         time: '35–40 mins',
//         categories: 'sandwich, Salads, wrap, Healthy...',
//         location: 'Civil Lines',
//         price: '₹119',
//     },
//     {
//         name: 'Barista Coffee',
//         rating: 4.7,
//         time: '25–30 mins',
//         categories: 'Beverages, Snacks, Desserts',
//         location: 'Civil Lines',
//         price: '₹190',
//     },
//     {
//         name: 'Pastas By Pizza Hut',
//         rating: 4.0,
//         time: '30–35 mins',
//         categories: 'Pastas',
//         location: 'Civil Lines',
//         price: '',
//     },
//     {
//         name: 'Makhani Darbar',
//         rating: 4.4,
//         time: '30–35 mins',
//         categories: 'Biryani, North Indian, Kebabs,...',
//         location: 'Stanley Road',
//         price: '₹99',
//     },
//     {
//         name: "Faasos' Signature W",
//         rating: 4.4,
//         time: '30–35 mins',
//         categories: 'Fast Food, Snacks, North Indian',
//         location: 'Civil Lines',
//         price: '₹129',
//     },
//     {
//         name: 'Subway',
//         rating: 4.3,
//         time: '35–40 mins',
//         categories: 'sandwich, Salads, wrap, Healthy...',
//         location: 'Civil Lines',
//         price: '₹119',
//     },
//     {
//         name: 'Barista Coffee',
//         rating: 4.7,
//         time: '25–30 mins',
//         categories: 'Beverages, Snacks, Desserts',
//         location: 'Civil Lines',
//         price: '₹190',
//     },
//     {
//         name: 'Pastas By Pizza Hut',
//         rating: 4.0,
//         time: '30–35 mins',
//         categories: 'Pastas',
//         location: 'Civil Lines',
//         price: '',
//     },
//     {
//         name: 'Makhani Darbar',
//         rating: 4.4,
//         time: '30–35 mins',
//         categories: 'Biryani, North Indian, Kebabs,...',
//         location: 'Stanley Road',
//         price: '₹99',
//     },
//     {
//         name: "Faasos' Signature W",
//         rating: 4.4,
//         time: '30–35 mins',
//         categories: 'Fast Food, Snacks, North Indian',
//         location: 'Civil Lines',
//         price: '₹129',
//     },
// ];

export const restaurants = [
    {
        id: 102,
        name: "Subway",
        rating: 4.3,
        offer: "60% OFF UPTO ₹110",
        address: "45A, Civil Lines, Prayagraj, UP",
        categories: "Sandwiches, Wraps, Salads, Beverages",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/5ece7fb2c731a0e1807ec5b40eda94f3",
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0ZyndB2qQY3HpT7fXSK93t_VSeUTgXepTlwD9Y3sEserhzbWozHzma49NFyVgaTrEtK4&usqp=CAU",
        contact: "+91 12345 67890",
        openTime: "10:00 AM – 10:00 PM",
        price: "₹119",
        description: "Subway is known for fresh and healthy sandwiches, wraps, and salads. Located in Civil Lines, it offers customizable meals and fast service.",
        items: [
            {
                id: 201,
                name: "Paneer Tikka Sub",
                price: "₹169",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/Autosuggest/Top%20200%20queries/Paneer%20Tikka.png",
            },
            {
                id: 202,
                name: "Veggie Delite Salad",
                price: "₹139",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/Autosuggest/Top%20200%20queries/salad.png",
            },
            {
                id: 203,
                name: "Chicken Teriyaki Wrap",
                price: "₹199",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/FOOD_CATALOG/IMAGES/CMS/2024/6/13/a24f286d-2971-41de-90b4-bb44eb24f4f2_51002a2d-95f7-4771-8a3f-5336ae01e723.jpg_compressed",
            },
            {
                id: 237,
                name: "Raj Kachori",
                price: "₹99",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/dcvd6gaieqo4hyatoawt",
            },
            {
                id: 238,
                name: "Chole Bhature",
                price: "₹129",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/fd7dca70d4280f1ddb12d023ebb9a214",
            },
            {
                id: 239,
                name: "Gulab Jamun",
                price: "₹79",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/0707bcbec2dcd2e062a042327ef43805",
            },
        ],
    },
    {
        id: 101,
        name: "Domino's Pizza",
        rating: 4.2,
        address: "Sardar Patel Marg, Civil Lines, Prayagraj, UP",
        categories: "Pizza, Italian, Fast Food",
        offer: "50% OFF UPTO ₹120",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/a3poc70wqkajnw3zxpsl",
        logo: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/RX_THUMBNAIL/IMAGES/VENDOR/2024/10/11/2726f357-5d56-4b8f-b6ed-609b79115353_971639.JPG",
        contact: "+91 98123 45678",
        openTime: "10:30 AM – 11:00 PM",
        price: "₹129",
        description: "Domino’s Pizza is known for its hot, cheesy pizzas, quick delivery, and combo offers. A pizza lover’s paradise.",
        items: [
            {
                id: 204,
                name: "Farmhouse Pizza",
                price: "₹229",
                image: "https://www.dominos.co.in/files/items/Farmhouse.jpg",
            },
            {
                id: 205,
                name: "Peppy Paneer Pizza",
                price: "₹249",
                image: "https://www.dominos.co.in/files/items/Peppy_Paneer.jpg",
            },
            {
                id: 206,
                name: "Garlic Breadsticks",
                price: "₹99",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/Autosuggest/Top%20200%20queries/Garlic%20Bread.png",
            },
        ],
    },
    {
        id: 103,
        name: "Haldiram's",
        rating: 4.5,
        address: "Katra, Prayagraj, UP",
        categories: "Indian Sweets, Snacks, North Indian",
        offer: "Flat ₹80 OFF",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/zhh9cj8n2eio7ottsq7e",
        logo: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/RX_THUMBNAIL/IMAGES/VENDOR/2024/7/18/310f0037-4124-4a7b-8d47-d44a8d569fa6_927307.jpg",
        contact: "+91 98712 33445",
        openTime: "9:00 AM – 10:00 PM",
        price: "₹129",
        description: "Haldiram's is renowned for traditional Indian sweets and savory snacks. A perfect place for quick bites and full meals.",
        items: [
            {
                id: 207,
                name: "Raj Kachori",
                price: "₹99",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/dcvd6gaieqo4hyatoawt",
            },
            {
                id: 208,
                name: "Chole Bhature",
                price: "₹129",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/fd7dca70d4280f1ddb12d023ebb9a214",
            },
            {
                id: 209,
                name: "Gulab Jamun",
                price: "₹79",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/0707bcbec2dcd2e062a042327ef43805",
            },
            {
                id: 234,
                name: "Paneer Tikka Sub",
                price: "₹169",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/Autosuggest/Top%20200%20queries/Paneer%20Tikka.png",
            },
            {
                id: 235,
                name: "Veggie Delite Salad",
                price: "₹139",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/Autosuggest/Top%20200%20queries/salad.png",
            },
            {
                id: 236,
                name: "Chicken Teriyaki Wrap",
                price: "₹199",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/FOOD_CATALOG/IMAGES/CMS/2024/6/13/a24f286d-2971-41de-90b4-bb44eb24f4f2_51002a2d-95f7-4771-8a3f-5336ae01e723.jpg_compressed",
            },
        ],
    },
    {
        id: 104,
        name: "Barista Coffee",
        rating: 4.7,
        address: "32B, Civil Lines, Prayagraj, UP",
        categories: "Beverages, Snacks, Desserts",
        offer: "Flat ₹100 OFF",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2025/6/16/41351416-7cc6-450c-9acf-98d74a451ca1_1122532.jpg",
        logo: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2025/6/16/41351416-7cc6-450c-9acf-98d74a451ca1_1122532.jpg",
        contact: "+91 98765 43210",
        openTime: "9:00 AM – 11:00 PM",
        price: "₹159",
        description: "Barista Coffee serves premium coffee, desserts, and bakery items. Ideal for casual meetings or quick coffee breaks.",
        items: [
            {
                id: 210,
                name: "Café Mocha",
                price: "₹150",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/rrlgw7897wioxwninbf5",
            },
            {
                id: 211,
                name: "Brownie Fudge",
                price: "₹120",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/cb96949738df465e570df971be74b1f1",
            },
            {
                id: 212,
                name: "Iced Latte",
                price: "₹140",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/FOOD_CATALOG/IMAGES/CMS/2025/3/7/7fc6d8fe-885d-41fa-8b24-0c3d3bdca763_41f1b0a2-6268-4d7a-a7a0-8a4f187c44ec.jpg",
            },
        ],
    },
    {
        id: 105,
        name: "Makhani Darbar",
        rating: 4.4,
        address: "12 Stanley Road, Prayagraj, UP",
        categories: "Biryani, North Indian, Kebabs",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/lm0zlhkxzjw1jtzqeuhe",
        logo: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/lm0zlhkxzjw1jtzqeuhe",
        contact: "+91 81234 56789",
        openTime: "11:00 AM – 11:30 PM",
        price: "₹99",
        description: "A family-style restaurant famous for Mughlai and North Indian delicacies with a spicy touch and rich flavors.",
        items: [
            {
                id: 213,
                name: "Chicken Dum Biryani",
                price: "₹199",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/FOOD_CATALOG/IMAGES/CMS/2025/2/19/7cd985b0-fffa-47cf-bab4-0fb00b43f0b8_4a8047c6-ea3e-4674-a76d-f745a4425b50.jpg",
            },
            {
                id: 214,
                name: "Paneer Butter Masala",
                price: "₹179",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/FOOD_CATALOG/IMAGES/CMS/2024/4/16/6922ae9c-5816-4309-9a80-ef752e699b8f_d0abd505-d098-43d4-a6a6-02a30574f299.jpg",
            },
            {
                id: 215,
                name: "Seekh Kebab",
                price: "₹149",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/130af5fa62459190fde7314034d0e6be",
            },
        ],
    },
    {
        id: 106,
        name: "Pastas By Pizza Hut",
        rating: 4.0,
        address: "Pizza Hut, Civil Lines Mall, Prayagraj, UP",
        categories: "Pastas, Italian",
        offer: "40% OFF UPTO ₹120",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2025/6/9/a1344928-c2cc-4223-92b9-d13f2fe9a749_508862.JPG",
        logo: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2025/6/9/a1344928-c2cc-4223-92b9-d13f2fe9a749_508862.JPG",
        contact: "+91 99888 77665",
        openTime: "11:00 AM – 11:00 PM",
        price: "₹219",
        description: "Hearty Italian meals from Pizza Hut’s pasta kitchen. Ideal for cheese lovers and pasta connoisseurs.",
        items: [
            {
                id: 216,
                name: "Red Sauce Pasta",
                price: "₹179",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/FOOD_CATALOG/IMAGES/CMS/2025/6/4/f91fe543-3b65-4419-88b5-5eb986354a5b_b3c7445b-8d14-4f09-9d44-a7be50f5b915.jpg",
            },
            {
                id: 217,
                name: "White Sauce Pasta",
                price: "₹189",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/FOOD_CATALOG/IMAGES/CMS/2024/8/16/8799b865-855a-4bed-b17d-c05d8f8e57c9_e0591dc8-a64b-4394-95ed-f4982697cd3f.JPG",
            },
            {
                id: 218,
                name: "Garlic Breadsticks",
                price: "₹99",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/gzg6apemrwbojfbpkxjv",
            },
        ],
    },
    {
        id: 107,
        name: "McDonald's",
        rating: 4.4,
        address: "Plot 4, Aliganj, Prayagraj, UP",
        categories: "Fast Food, Beverages",
        offer: "60% OFF UPTO ₹110",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2025/1/9/40408979-8937-40d6-9ca9-d9af67a23391_253769.JPG",
        logo: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/n9bkfix37ohwikvjlzyg",
        contact: "+91 77665 11223",
        openTime: "10:00 AM – 11:00 PM",
        price: "₹109",
        description: "Global fast food brand offering burgers, fries, soft drinks, and more. Famous for quick bites and classic taste.",
        items: [
            {
                id: 219,
                name: "McVeggie Burger",
                price: "₹99",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/Autosuggest/Top%20200%20queries/Burger.png",
            },
            {
                id: 220,
                name: "Coke Float",
                price: "₹79",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/FOOD_CATALOG/IMAGES/CMS/2025/2/26/b33e1219-1f1e-44aa-8fa2-9f00563b0f88_a59af975-708a-4ec5-8ed4-8035398bfbc0.jpg",
            },
            {
                id: 221,
                name: "McChicken",
                price: "₹129",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/FOOD_CATALOG/IMAGES/CMS/2024/4/19/d4387d28-73ab-45b7-b424-61588863d158_9477217d-7c7a-4834-919a-b9ae7d7cf950.jpg",
            },
        ],
    },
    {
        id: 108,
        name: "Burger King",
        rating: 4.3,
        address: "Shop 9, Civil Lines, Prayagraj, UP",
        categories: "Burgers, American",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2025/6/18/90239691-25e8-4701-abab-2878abd08091_437010.jpg",
        logo: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2025/6/18/90239691-25e8-4701-abab-2878abd08091_437010.jpg",
        contact: "+91 78901 23456",
        openTime: "10:30 AM – 11:00 PM",
        price: "₹149",
        description: "Flame-grilled burgers, crispy fries, and chilled shakes. Burger King is the go-to for American fast food lovers.",
        items: [
            {
                id: 222,
                name: "Whopper",
                price: "₹159",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/FOOD_CATALOG/IMAGES/CMS/2024/4/19/d4387d28-73ab-45b7-b424-61588863d158_9477217d-7c7a-4834-919a-b9ae7d7cf950.jpg",
            },
            {
                id: 223,
                name: "Crispy Veg Burger",
                price: "₹79",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/ki6enhbsj4nlpux4rpfb",
            },
            {
                id: 224,
                name: "Chocolate Shake",
                price: "₹119",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/Autosuggest/Top%20200%20queries/Shake.png",
            },
        ],
    },
    {
        id: 109,
        name: "Paradise Biryani",
        rating: 4.5,
        address: "Mahanagar, Prayagraj, UP",
        categories: "Biryani, Indian",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/krn2uala8oo04m4bigz2",
        logo: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/gxghope8gkvkyyhicv0p",
        contact: "+91 66554 77889",
        openTime: "11:00 AM – 10:30 PM",
        price: "₹179",
        description: "Legendary biryani chain with aromatic rice dishes, Indian curries, and kebabs. A must-visit for Biryani lovers.",
        items: [
            {
                id: 225,
                name: "Hyderabadi Mutton Biryani",
                price: "₹259",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/FOOD_CATALOG/IMAGES/CMS/2024/7/2/d0d58607-091d-4943-b38c-be131e15cff2_795d7c6b-d856-478e-ab49-ae2f8856d949.jpeg",
            },
            {
                id: 226,
                name: "Chicken 65",
                price: "₹179",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/Autosuggest/Top%20200%20queries/Biryani.png",
            },
            {
                id: 227,
                name: "Veg Dum Biryani",
                price: "₹149",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/Autosuggest/Top%20200%20queries/Veg%20Biryani.png",
            },
        ],
    },
    {
        id: 110,
        name: "Theobroma",
        rating: 4.3,
        address: "Civil Lines, Prayagraj, UP",
        categories: "Bakery, Desserts, Beverages",
        offer: "ITEMS AT ₹49",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2025/6/23/c6b15c97-d691-4f6a-8fa4-67952fcf7a7d_916151.JPG",
        logo: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2025/6/23/c6b15c97-d691-4f6a-8fa4-67952fcf7a7d_916151.JPG",
        contact: "+91 91234 56780",
        openTime: "9:00 AM – 11:00 PM",
        price: "₹49",
        description: "Famous for brownies, cakes, and gourmet desserts, Theobroma brings a taste of luxury with quick delivery and high quality.",
        items: [
            {
                id: 228,
                name: "Brownie Bliss",
                price: "₹49",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/pzne4rftcikm2igco2a2",
            },
            {
                id: 229,
                name: "Chocolate Mousse Cup",
                price: "₹79",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/mleunddwzr8ergde6tn6",
            },
            {
                id: 230,
                name: "Red Velvet Pastry",
                price: "₹89",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/FOOD_CATALOG/IMAGES/CMS/2025/6/18/9e8d33ad-5223-4aba-b1f3-56fa975e845e_7094787b-a6f5-49e8-a848-f54c2b8221d5.jpeg",
            },
        ],
    },
    {
        id: 111,
        name: "NIC Ice Creams",
        rating: 4.7,
        address: "Civil Lines, Prayagraj, UP",
        categories: "Ice Cream, Desserts",
        offer: "ITEMS AT ₹124",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2025/7/8/468558bf-cebc-43fd-b366-6f7786b76f9f_392164.JPG",
        logo: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2025/7/8/468558bf-cebc-43fd-b366-6f7786b76f9f_392164.JPG",
        contact: "+91 90000 11122",
        openTime: "11:00 AM – 11:00 PM",
        price: "₹124",
        description: "Premium handcrafted ice creams made with natural ingredients and rich flavors delivered fresh.",
        items: [
            {
                id: 231,
                name: "Tender Coconut Ice Cream",
                price: "₹124",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/krjz4qivuf8sigdfqkbq",
            },
            {
                id: 232,
                name: "Alphonso Mango",
                price: "₹124",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/Autosuggest/Mango%20Desserts",
            },
            {
                id: 233,
                name: "Chocolate Chips",
                price: "₹124",
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/hlam5ip2re0gu4mieypa",
            },
        ],
    }
]
export const topDishes = [
    {
        id: 201,
        name: 'Chicken Biryani',
        rating: 4.6,
        price: '₹199',
        category: 'Biryani, Mughlai',
        restaurant: 'Makhani Darbar',
        brand_id: 105,
        location: 'Stanley Road',
        time: '30–35 mins',
        image: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2025/1/21/e73c3925-720a-47c5-a9b9-3968ac874bc6_1030958.JPG'
    },

    {
        id: 202,
        name: 'Paneer Wrap',
        rating: 4.2,
        price: '₹129',
        category: 'Wraps, Fast Food',
        restaurant: "Faasos' Signature W",
        brand_id: 101, // Faasos' Signature W's id
        location: 'Civil Lines',
        time: '25–30 mins',
        image: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/11/15/382182e7-b4d7-4127-9168-1972545358ef_442055.jpg'
    },

    {
        id: 203,
        name: 'Cold Coffee',
        rating: 4.8,
        price: '₹150',
        category: 'Beverages, Coffee',
        restaurant: 'Barista Coffee',
        brand_id: 104, // Barista Coffee's id
        location: 'Civil Lines',
        time: '20–25 mins',
        image: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2025/6/16/41351416-7cc6-450c-9acf-98d74a451ca1_1122532.jpg'
    },

    {
        id: 204,
        name: 'Veggie Delight Sub',
        rating: 4.4,
        price: '₹119',
        category: 'Sandwich, Healthy',
        restaurant: 'Subway',
        brand_id: 106, // Subway's id
        location: 'Civil Lines',
        time: '35–40 mins',
        image: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/f9139d81371fb601d81c77d9004b0a97'
    },

    {
        id: 205,
        name: 'Red Sauce Pasta',
        rating: 4.1,
        price: '₹179',
        category: 'Pasta, Italian',
        restaurant: 'Pastas By Pizza Hut',
        brand_id: 107, // Pizza Hut's id
        location: 'Civil Lines',
        time: '30–35 mins',
        image: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2025/5/26/dcc0130c-c30b-4487-96ab-95fb76c218e1_1102127.jpg'
    },

    {
        id: 206,
        name: 'Gulab Jamun',
        rating: 4.7,
        price: '₹90',
        category: 'Dessert, Indian Sweets',
        restaurant: 'Makhani Darbar',
        brand_id: 105, // Makhani Darbar's id
        location: 'Stanley Road',
        time: '30–35 mins',
        image: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2025/6/12/f64a0894-8c30-4076-8bde-bd13d8c60f57_1056344.jpg'
    },

    {
        id: 207,
        name: 'Chicken Shawarma',
        rating: 4.5,
        price: '₹139',
        category: 'Middle Eastern, Fast Food',
        restaurant: "Faasos' Signature W",
        brand_id: 101, // Faasos' Signature W's id
        location: 'Civil Lines',
        time: '30–35 mins',
        image: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/12/20/7ea9448a-b052-430a-8097-ff8e64e3bd8c_902227.jpg'
    },

    {
        id: 208,
        name: 'Garlic Bread',
        rating: 4.3,
        price: '₹99',
        category: 'Snacks, Bakery',
        restaurant: 'Pastas By Pizza Hut',
        brand_id: 107, // Pizza Hut's id
        location: 'Civil Lines',
        time: '30–35 mins',
        image: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/a5d83a2930098487271ad754c001439a'
    },

    {
        id: 209,
        name: 'Chocolate Brownie',
        rating: 4.6,
        price: '₹110',
        category: 'Desserts, Bakery',
        restaurant: 'Barista Coffee',
        brand_id: 104, // Barista Coffee's id
        location: 'Civil Lines',
        time: '25–30 mins',
        image: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/xmzzh2rr0gnqo9zkrs2g'
    },

    {
        id: 210,
        name: 'Aloo Patty Sub',
        rating: 4.2,
        price: '₹119',
        category: 'Sandwich, Healthy',
        restaurant: 'Subway',
        brand_id: 106, 
        location: 'Civil Lines',
        time: '35–40 mins',
        image: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/r4zqsagkgaktmp4epzvz'
    },
];


export const heroData = {
    title1: 'Burger King',
    desc1: 'Famous for its flame-grilled burgers and fast food offerings.',
    img1: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGlCud4byZs8YI03BsWzGWOqsX29vCp35bCA&s',
    link1: '/restaurants/108',

    title2: 'Pizza Hut',
    desc2: 'Known for its delicious range of pizzas, pastas, and sides.',
    img2: 'https://upload.wikimedia.org/wikipedia/commons/1/17/Pizza_Hut_international_logo_2014.svg',
    link2: '/restaurants/106',

    title3: `McDonald's`,
    desc3: 'Global fast food chain offering burgers, fries, and happy meals.',
    img3: 'https://logos-world.net/wp-content/uploads/2020/04/McDonalds-Logo.png',
    link3: '/restaurants/107',

    title4: 'Subway',
    desc4: 'Popular for its customizable submarine sandwiches and healthy options.',
    img4: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0ZyndB2qQY3HpT7fXSK93t_VSeUTgXepTlwD9Y3sEserhzbWozHzma49NFyVgaTrEtK4&usqp=CAU',
    link4: '/restaurants/102',

    title5: 'Paradise',
    desc5: 'Renowned for its Hyderabadi biryani and authentic Indian cuisine.',
    img5: 'https://www.paradisefoodcourt.in/images/logos/Paradise-Logo.png', 
    link5: '/restaurants/109'
};

export const offers = [
    {
        id: 1,
        title: "50% Off on Pizza",
        description: "Get 50% off on all pizzas at Domino's.",
        details: "Valid until the end of the month. Use code PIZZA50.",
        image: "https://www.dominos.co.in/files/items/Farmhouse.jpg",
    },
    {
        id: 2,
        title: "Buy 1 Get 1 Free",
        description: "Buy one sandwich and get another free at Subway.",
        details: "Limited time offer. No code required.",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/RX_THUMBNAIL/IMAGES/VENDOR/2025/6/12/584ef1aa-c1d9-42ac-8f4e-ea1d7c7e1f73_80418.jpg",
    },
    {
        id: 3,
        title: "Flat ₹100 Off on Orders Above ₹500",
        description: "Enjoy flat ₹100 off on your next order at Haldiram's.",
        details: "Valid until July 31, 2025. Use code HALDIRAM100.",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/RX_THUMBNAIL/IMAGES/VENDOR/2024/7/18/310f0037-4124-4a7b-8d47-d44a8d569fa6_927307.jpg",
    },
    {
        id: 4,
        title: "20% Off on All Beverages",
        description: "Get 20% off on all beverages at Barista Coffee.",
        details: "Offer valid all week. No code required.",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/RX_THUMBNAIL/IMAGES/VENDOR/2025/7/4/98c34c82-df93-4298-bbb4-984856f9397f_240249.JPG",
    },
    {
        id: 5,
        title: "Free Dessert with Every Meal",
        description: "Get a free dessert with every meal at McDonald's.",
        details: "Limited time offer. No code required.",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/RX_THUMBNAIL/IMAGES/VENDOR/2025/1/9/40408979-8937-40d6-9ca9-d9af67a23391_253769.JPG",
    },
    {
        id: 6,
        title: "30% Off on All Orders",
        description: "Get 30% off on all orders at KFC.",
        details: "Valid until the end of the month. Use code KFC30.",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/RX_THUMBNAIL/IMAGES/VENDOR/2024/12/9/84b66a02-1b7f-4ac3-9976-4ac3c8633c57_82234.JPG",
    },
    {
        id: 7,
        title: "Buy 2 Get 1 Free",
        description: "Buy two drinks and get one free at Barista.",
        details: "Limited time offer. No code required.",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_112,h_112,c_fill/RX_THUMBNAIL/IMAGES/VENDOR/2025/7/4/98c34c82-df93-4298-bbb4-984856f9397f_240249.JPG",
    },
];


